{{ if and .Values.imagebuilder.enabled .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flightctl-imagebuilder
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
{{ end }}

