{{ if and .Values.imagebuilder.enabled .Values.global.rbac.create }}
---
# Role to allow imagebuilder to check migration job status in flightctl-internal namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-imagebuilder-migration-reader
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-imagebuilder-migration-reader
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightctl-imagebuilder-migration-reader
subjects:
  - kind: ServiceAccount
    name: flightctl-imagebuilder
    namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
{{ end }}

